server {
    listen 80;
    server_name localhost;

    root /var/www/public;
    index index.php index.html;

    # Логирование
    error_log  /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;

    # Основной маршрутизатор
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
        gzip_static on;
    }

    # Обработка PHP
    location ~ \.php$ {
        # Разделение пути для PATH_INFO
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # Передача запроса в контейнер с PHP
        fastcgi_pass api_app:9000;
        fastcgi_index index.php;

        # Настройки переменных
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # Оптимизация буферизации (полезно для больших ответов)
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }

    # Запрет доступа к скрытым файлам
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
